import { nanoid } from "nanoid";

const hardwareItems = () => {
  return [
    // !pdfs and the other inpage content will also be included in this  (another array can be made in the items array!)
    {
      id: 1,
      name: "paints",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1661368469/PTC/hardware/Asian-paints-1_szd9bd.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662402461/PTC/hardware/asian_paints_4_dqljma.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1661368458/PTC/hardware/asian-paints-3_uh9amv.webp",
      ],
      seller: "Asian Paints",
      pdf: "https://drive.google.com/file/d/1Z-y7C662i2rTZCoDdiW4rzEik1IZFg_S/view?usp=sharing",
      desp: "The company has come a long way since its small beginnings in 1942. It was set up as a partnership firm by four friends who were willing to take on the world's biggest, most famous paint companies operating in India at that time. Over the course of 25 years, Asian Paints became a corporate force and India's leading paints company. Driven by its strong consumer-focus and innovative spirit, the company has been the market leader in paints since 1967. Today, it is double the size of any other paint company in India. Asian Paints manufactures a wide range of paints for decorative and industrial use and also offers Wall Coverings, adhesives and services under its portfolio. The company is also present in the Home Improvement and Decor segment and offers bath and kitchen products.  The company also introduced lightings, furnishings and furniture in its portfolio.  In the Health and Hygiene segment, Asian Paints offers range of Sanitizers and Surface Disinfectants.",
      link: "https://www.asianpaints.com/",
      category: "hardware",
    },
    {
      id: 2,
      name: "power tools",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662402751/PTC/hardware/powertools_tj0onb.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662402760/PTC/hardware/power_tools_2_insype.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662402754/PTC/hardware/power_tools_3_whasuh.jpg",
      ],
      seller: "JCB",
      pdf: "https://drive.google.com/file/d/18P1HQUgJpDLOwfrQTZwca3RZaP_zx8Yn/view?usp=sharing",
      desp: "JCB India Limited is a leading manufacturer of earthmoving and construction equipment in India. The company started as a joint venture in 1979 and is now a fully owned subsidiary of J.C Bamford Excavators, United Kingdom. With five state-of-the-art factories in India, JCB manufactures a wide range of world-class equipment in India for the domestic market as well as for exports to more than 110 countries. JCB introduced the iconic Backhoe Loader in India over four decades ago. It has since expanded its range to over 60 products in nine categories. The Ballabgarh factory near New Delhi, which is the world’s largest factory for Backhoe Loaders, is also the Headquarters for JCB India. This facility, apart from Backhoe Loaders, also manufactures Skid Steer Loaders, Telehandlers, Diesel Generators and Diesel Engines. ",
      link: "http://powertools.jcb-tools.in/",
      category: "hardware",
    },
    {
      id: 3,
      name: "waterproofing items",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1661370131/PTC/hardware/waterproofing_items_cg6wba.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662402934/PTC/hardware/waterproofing_items_2_rg5sen.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658063346/PTC/hardware/fosroc-waterproofing-chemicals-500x500-500x500_pl03mq.webp",
      ],
      seller: "Fosroc",
      pdf: "https://drive.google.com/file/d/1zIWcslvV3pxN8LlX6g41dsqhV4rJXxJ0/view?usp=sharing",
      desp: "Fosroc is a world leader in manufacturing and supplying high performance chemicals for the construction industry. We deliver complete constructive solutions for all project needs. Fosroc India is a 100% privately owned subsidiary of Fosroc International Limited UK, a division of JMH Group, with over 80 years of experience worldwide. Fosroc India has over four decades of pioneering experience in providing Constructive Solutions and serving customers in the construction industry across the country. We have state-of-the-art manufacturing facilities in Bangalore (Karnataka), Ankleshwar (Gujarat), Kolkata (West Bengal) and Keshwana (Rajasthan), with a wide network of sales and marketing offices in all metropolitan areas and leading cities in India, supported by mix design and specification experts, regional technical service specialists and regional concrete laboratories. Fosroc’s corporate and registered offices are based in Bangalore.",
      link: "https://fosroc.com/english/about-fosroc-india",
      category: "hardware",
    },
    {
      id: 4,
      name: "Hight Tensile Fasteners",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1661368906/PTC/hardware/High-Tensile-Fasteners-3_juazni.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1661368880/PTC/hardware/High-Tensile-Fasteners_ptp7vk.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1661368932/PTC/hardware/High-Tensile-Fasteners-2_byudyc.webp",
      ],
      seller: "Caparo India Pvt Ltd",
      pdf: "https://drive.google.com/drive/folders/1RpvEXT56lneQ5myoaR0Z7H5zhGHIO_Zn",
      desp: "Established in 2005 at Chopanki (Bhiwadi), Rajasthan, Caparo's fasteners division is among the market leaders in fasteners technology in India. As a specialist in in-house manufacturing of a wide range of high-tensile standard and special fasteners, the division has established itself as a reliable supplier of fasteners to almost all the Automobile OEMs in the country and their manufacturing locations abroad. Known for our solutions-driven know-how and zero-defects policy, we produce fasteners for a variety of international and Indian standards from cold heading quality of Medium Carbon, High Carbon & Alloy Steel. As a process-driven and IATF 16949, ISO 45001 & ISO 14001 certified facility , our primary focus is to provide the best solutions to our customers, with new product development being our hallmark. As a result, we have developed a wide range of products catering to the needs of the automobile as well as general engineering applications.",
      link: "https://www.caparo.co.in/fasteners/",
      category: "hardware",
    },
    {
      id: 5,
      name: "Pin & Chemical Fasteners",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1661369769/PTC/hardware/pin-chemical-fasteners-2_oc7goi.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1661369766/PTC/hardware/pin-chemical-fasteners_jsosfp.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403144/PTC/hardware/pin_chemical_fasteners_3_mymxbu.webp",
      ],
      seller: "Caparo India Pvt Ltd",
      pdf: "https://drive.google.com/drive/folders/1_4IrGebyQOUjJtngvD4z4ane2t2OxVQ5?usp=sharing",
      desp: "Established in 2005 at Chopanki (Bhiwadi), Rajasthan, Caparo's fasteners division is among the market leaders in fasteners technology in India. As a specialist in in-house manufacturing of a wide range of high-tensile standard and special fasteners, the division has established itself as a reliable supplier of fasteners to almost all the Automobile OEMs in the country and their manufacturing locations abroad. Known for our solutions-driven know-how and zero-defects policy, we produce fasteners for a variety of international and Indian standards from cold heading quality of Medium Carbon, High Carbon & Alloy Steel. As a process-driven and IATF 16949, ISO 45001 & ISO 14001 certified facility , our primary focus is to provide the best solutions to our customers, with new product development being our hallmark. As a result, we have developed a wide range of products catering to the needs of the automobile as well as general engineering applications.",
      link: "https://www.caparo.co.in/fasteners/",
      category: "hardware",
    },
    {
      id: 6,
      name: "lifting items",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656180902/PTC/hardware/Lifting_items_fxctrd.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658061146/PTC/hardware/fire-and-safety-products-500x500_jsvdvl.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658061152/PTC/hardware/product-jpeg-500x500_ze0gy9.webp",
      ],
      seller: "Ferreterro",
      pdf: "https://drive.google.com/file/d/1J1dmHqWd_NiYxxi4m6ZXww2AATjbXM7x/view?usp=sharing",
      desp: "Our roots are more than 135 years deep, with being Delhi’s first Foundry and then being Worlds largest manufacturer of spanners and hand tools with 7000 workforce. We started manufacturing hardware fittings with a British collaboration which we took over and expanded into manufacturing and exporting of Lifting, Lashing, Hoists, Tie down restraint, Safety and defence products. We have a diverse manufacturing portfolio. Manufacturing right from Webbing Slings to round slings, Own High Tenacity Polyester Yarn, Steel Chains, Snow Chains, Non Skid Chains, Chain Pulley blocks, Electric chain hoists, Gears, Compensation chains for elevator industry, Tyre chains, Aircraft arrester Nets, Cargo Bars, Purchase tapes, Shoulder dolly, Cam buckles, Ratchet lashing buckles and hooks, One way buckles, Drop forged buckles, Shackles, Air dunnage bags, composite straps, Fall Arrest safety harness belts and all hardware for same, Wire buckles and many more.",
      link: "https://ferreterro.com/about-us/",
      category: "hardware",
    },
    {
      id: 7,
      name: "NVR Valves",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403275/PTC/hardware/NVR_valves_1_geoyku.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403276/PTC/hardware/NVR_Valves_2_lkx8w1.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403277/PTC/hardware/NVR_valves_3_a57she.jpg",
      ],
      seller: "NVR",
      pdf: "https://drive.google.com/file/d/1z9qixXmarjG6_k0sFejONYfzIzdGRtz7/view?usp=sharing",
      desp: "Avn manufacturing an iso 9001.2015 is a global company offering a wide range of water and wastewater infrastructure products, fire protection and oem products for well over two decades in domestic and overseas market under the brand name “nvr”. We are lead sellers in most of the markets under our operation and are identified by our innovative quality and supply chain management. With the “commitment to excellence “drive, nvr is one of the foremost name in bronze, brass, cast iron, cast steel, forged steel, ductile iron and mallaeable galvanized products for domestic and international industrial applications.",
      link: "https://nvrfittings.com/about-us/",
      category: "hardware",
    },
    {
      id: 8,
      name: "Pipe fittings",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403639/PTC/hardware/UNIK_pipe_fittings_2_xanjwt.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403639/PTC/hardware/UNIK_pipe_fittings_1_j3ks8x.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403639/PTC/hardware/UNIK_pipe_fittings_3_ehrnyk.jpg",
      ],
      seller: "UNIK",
      pdf: "https://drive.google.com/file/d/1T7_CqqRgvcRxdXiHQ5pUgNEWe9m_Vijt/view?usp=sharing",
      desp: "“Unique Pipe Fitting Company” is one the leading manufacturers of Malleable Iron Galvanized Pipe Fittings in India. Our modern factory is equipped with upto date plant, machinery and inspection equipment, skilled craftsmanship, plus rigid inspection throughout all stages of manufacturing ensures the high standard of accuracy now associated with all “UNIK” Pipe Fittings. Our partners are large scale stockist, Distributors all over India. We are striving to be an efficient and reliable partners to our customers. It is our aim to continuously upgrade our Production technique in order to offer our Stockist/ Distributors and consumers an excellence quality at reasonable price.",
      link: "http://www.unikpipefittings.com/about-us.html",
      category: "hardware",
    },
    {
      id: 9,
      name: "packaging items",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181316/PTC/hardware/packge_yy3f3z.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403947/PTC/hardware/Copy_of_packaging_items_mavevr.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662403947/PTC/hardware/packaging_items_1_wqvwcg.jpg",
      ],
      seller: "Twin Tech",
      pdf: "https://drive.google.com/file/d/1Ry6-ljPHWeRBqAPB_n2KiBpUIX6DS4cd/view?usp=sharing",
      desp: "win Tech India Pvt. Ltd is a leading name in manufacturing and supplying of aerosols and sprays in a multitude of industrial application. Biodegradable, user & environment friendly, all our sprays are custom designed for easy use. We promote our aerosols for different applications under the registered brand name of SPRAYZET. We also do contract aerosol packaging for a variety of companies and industries, with extensive private label aerosol filling / packaging capabilities. “Twin Tech” is the manufacturer, exporter & supplier of specialty industrial maintenance aerosols like On-Line Contact Cleaner, Carbon Remover, Electronic Cleaner, Insulating Spray Varnish, Bus-Bar Coatings, Penetrating Oil, Moisture Displacer, Rust Preservatives, Rust-Remover, Anti-Seize Compound, Silicon-Free Mould Release Agent, Mould & Die Protector, Mould Cleaner, Galvanizing Coating, etc.",
      link: "https://www.twinindia.com/",
      category: "hardware",
    },
    {
      id: 10,
      name: "air & PU Fittings",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656180758/PTC/hardware/air_fittings_nsnlau.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662404088/PTC/hardware/Air_and_PU_fittings_2_xdlrmf.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662404088/PTC/hardware/Air_and_PU_fittings_3_yqtlxg.jpg",
      ],
      seller: "Techno",
      pdf: "https://drive.google.com/file/d/1QLYyIc5abo1XjKYVs4rw2j2mctuhW51f/view?usp=sharing",
      desp: "We would like to introduce ourselves as a dealer of Pneumatics Products for last 25 years and have luanched imported Pneumatics Products since last three years. We have a full stock of Directional Control Valves, Diaphragm Valves, Pilot and Direct Acting Solenoid Valves, Manual, Mechanical and Automatic Valves, Auto Drain Valve, High Pressure Filter & Regulator, Air Treatment Units, Push-inTube Fittings, Silencers, Air guns, Brass One Touch Couplers, Hose Reel, Spring Balancers etc. to meet and satisfy every customer needs. All the products, we import are manufactured by the Companies who possess ISO 9001-2000 International Quality System Attestation. Techno Pneumatics is in coordination with these companies, who use their technological strength and rich professional experiences and launch latest products.",
      link: "http://www.techno-pneumatics.com/default.aspx",
      category: "hardware",
    },
    {
      id: 11,
      name: "HP Screws",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662404392/PTC/hardware/HP_screws_1_wsszrf.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662404392/PTC/hardware/HP_screws_3_j56xj6.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662404392/PTC/hardware/HP_screws_2_yzic52.webp",
      ],
      seller: "HP",
      pdf: "https://drive.google.com/file/d/1QLYyIc5abo1XjKYVs4rw2j2mctuhW51f/view?usp=sharing",
      desp: "Established in 2007, Landmark Crafts Pvt Ltd, an ISO 9001:2015 accredited company is located at Anand Industrial Estate, Ghaziabad Uttar Pradesh India. It is located next to New Delhi, Capital of India and enjoys convenient transportation. Landmark Crafts Pvt. Ltd. is also rated SME-2 by CRISIL. As one of the largest manufacturers of Self Drilling Screws ,Dry Wall Screws & Aluminum Blind Rivets.The Company is committed to achieving client’s satisfaction by consistently meeting their specific requirements in terms of quality, cost effectiveness, and timely delivery. The company achieves this through continued training and adoption to new technology. Landmark Crafts (P) Ltd.has two manufacturing units and currently employees around 50 senior technicians. The factory at Anand Industrial Estate is engaged in manufacturing of Aluminum Blind Rivets SDS & Dry wall and the one at Baddi (H.P) is engaged in the production of SDS.",
      link: "https://www.landmarkcrafts.co.in/about-us.html",
      category: "hardware",
    },
    {
      id: 12,
      name: "HSS Drills and Tap Sets",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662404857/PTC/hardware/HSS_drills_and_tap_set_ezlhcq.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662404857/PTC/hardware/HSS_drills_and_tap_set_2_gykm5v.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662404857/PTC/hardware/HSS_drills_and_tap_set_3_xbyawu.jpg",
      ],
      seller: "HSS",
      pdf: "https://drive.google.com/file/d/1pyn0rexQLQYOxUkuAF5J7hgaKn7Es7U8/view?usp=sharing",
      desp: "Addison & Co is part of the 148-year-old legacy of the Amalgamations group, a much esteemed and venerated name among business houses in India. The group has operations in a broad range of industries, varying from Heavy engineering and manufacturing to logistics and finance. Addison & Co have been pioneers in cutting tool research, development, manufacture and exports in India since 1955. At Addison, we manufacture our cutting tools with strict adherence to global standards at a state-of-the-art factory in Chennai, India. A rigorous quality control regime, efficient supply chains and an ear for customer feedback have made us the preferred tooling partners for our demanding customers in Europe, USA, Japan and other quality conscious markets across the world.",
      link: "http://www.addison.co.in/aboutus.html",
      category: "hardware",
    },
    {
      id: 13,
      name: "Welding Rods",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662405209/PTC/hardware/welding_rods_3_pmrsld.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662405209/PTC/hardware/welding_rods_2_zttshw.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662405209/PTC/hardware/welding_rods_1_tp7xfj.jpg",
      ],
      seller: "ADOR",
      pdf: "https://drive.google.com/file/d/151XZaXA4LHvKbhJGx-3VRd2PjF5LDQmh/view?usp=sharing",
      desp: "Established in 1951, Ador (formerly, Advani-Oerlikon) is one of the leading welding companies in India, manufacturing high-quality welding equipment, consumables, and welding automation solutions. Additionally, Ador has been in the Flares & Process Equipment Division for more than 30+ years. Ador has played a significant role during the post-independence industrialization in India and takes immense pride in its heritage.",
      link: "https://www.adorwelding.com/who-we-are/",
      category: "hardware",
    },
    {
      id: 14,
      name: "Wire Ropes & Sling",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662833837/PTC/hardware/Wire_rope_and_sling_2_izegqp.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662833838/PTC/hardware/Wire_rope_and_sling_1_xrr7ob.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662833838/PTC/hardware/Wire_rope_and_sling_3_cnrqgc.jpg",
      ],
      seller: "Mahadev",
      pdf: "https://drive.google.com/file/d/13aT0spUccM-ue2_2t5ouj7cfQy1JqLIb/view?usp=sharing",
      desp: "An ISO 9001:2015 and BIS/ISI certified company Mahadev Industries is one of the leading Steel Wire Rope manufacturer in India. Mahadev Industries has won recognition from lot of its users/departments/testing institution/customers. We are MSME / SSI Unit. It born in 1995 and started working at Alipur, Delhi with a covered area of 7500Sq.ft.and Then shifted to Uttar Pradesh State Industrial Development- Tronica City, Loni, Ghaziabad (UP) in the year 2002 with a covered area of 25000 Sq.ft. due to lack of space then in 2006 extended the work shed from 25000 Sq.ft. to 50000 Sq.ft. Mahadev Industries has in –house production plant with in-house testing facilities to ensure that everything is up to the mark of specified standards. This self-assurance comes from the strong infra structural and technological capabilities. It has state of art machineries and fully equipped testing labs for continuous process testing from raw material to finished goods according to National and International Standards and for this we can say rather we are proud of having breaking load capacity of 300 M.T. with crimping machine (for slings) up to 2000 M.T., and to complement it further there is an in-house test laboratory having a full range of facilities for chemical analysis and mechanical testing of wire, wire ropes and other allied articles/accessories. Highly skilled workforce reflects Mahadev’s commitments to continuously serve its customers and to produce high performance and cost effective.",
      link: "https://www.mahadevropes.com/about.html",
      category: "hardware",
    },
    {
      id: 15,
      name: "Safety Items",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662834476/PTC/hardware/Safety_item_1_dw6bcn.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662834476/PTC/hardware/Safety_item_2_qodvnp.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662834476/PTC/hardware/Safety_item_3_fcfxyo.jpg",
      ],
      seller: "Metro",
      pdf: "https://drive.google.com/file/d/1uxbcDPw1efYA9pkZIsvxs_xhvhE_6xj6/view?usp=sharing",
      desp: "Incepted in the year 1998, Metro Safety India Pvt Ltd  is one of the leading manufacturers and suppliers of industrial safety helmets, belts and harnesses, welding accessories and other road safety products such as speed bumps, road barriers, reflective jackets and safety batons. These include safety boots & gloves, speed bumps, studs & safety batons, life jackets & life bouy, metal detector, industrial safety belts, safety net & ladder, road safety products, reflective jackets & tape, road barriers, safety helmets for mine industry, and helmets & side boxes. We specialize in manufacturing Fiberglass Reinforced Plastic (FRP) helmets, which are known for its high quality standard. Our team of research analysts is constantly working to develop new and enhanced range of helmets that are assured to have anti - scratch, anti glare and anti-fog visors. Thus, our industrial safety helmets are successfully meeting the needs of mine industry, roadways, and construction industry.",
      link: "https://www.metrosafetyindia.co/about-us.html",
      category: "hardware",
    },
    {
      id: 16,
      name: "SS Nut Bolt",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662835013/PTC/hardware/SS_nut_bolt_2_fs1cj8.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662835012/PTC/hardware/SS_nut_bolt_1_wwrent.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662835012/PTC/hardware/SS_nut_bolt_3_udlftc.jpg",
      ],
      seller: "Suraj",
      pdf: "https://drive.google.com/file/d/1irBdVEFPUh-eybyNFpzl6fg46m-urrY4/view?usp=sharing",
      desp: "Suraj Metal Corporation was established in the year 1973 with the aim of catering to the growing demands of Stainless Steel and Nickel Alloys. Suraj Metal Corporation is a leading supplier of various Stainless Steel and Nickel Alloys products including Round Bars, Forging and Fasteners. We have a team of young visionaries who endeavor for excellence in every aspect related to metals. We strongly believe in our core values and are always in the pursuit of success along the lines of ethical business practices. Keeping in mind its customer centric approach, timely delivery and quality products, the Company has grown in size and products range. Over the decades Suraj Metal Corporation has provided immense support to this industry In India and has built various congenial customer relations. Now with the new generation of entrepreneurs joining the company, the company aims at expanding on a global scale with the domestic supply and export of Stainless Steel and Nickel Alloys Round Bar, Sheet , Plate and Coil.",
      link: "https://www.surajmetal.com/about.html",
      category: "hardware",
    },
    {
      id: 17,
      name: "PVC Duct & Thunder Hose Pipe",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662836152/PTC/hardware/Thunder_and_hose_pipe_3_e6gg4w.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662836152/PTC/hardware/Thunder_and_hose_pipe_1_luphbd.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662836152/PTC/hardware/Thunder_and_hose_pipe_2_aplpsr.jpg",
      ],
      seller: "Puneet Trading Company",
      pdf: "https://drive.google.com/file/d/10MHtiP7RJPMvtaKDUswNOaNMLn_-q63S/view?usp=sharing",
      desp: "It all started way back in 1993 when we had commenced our firm and named it “Punit Trading Company” with a motive of making every hardware-related product available in one place. Then, the motive started expanding with the expansion of our store from a small one consisting of only a few accessories to a large store with our godowns as well. In the meantime, we partnered with some prestigious brands like Asian paints, Berger paints, TATA Agrico, UNIK, JCB, and many more to give variety to our customers. Now, a family-owned and operated business has become the region’s best distributor especially in hardware products that support industrial houses and manufacturers for all their requirements.",
      link: "https://www.ptchardware.com/about",
      category: "hardware",
    },
    {
      id: 18,
      name: "SS Pipes",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662838221/PTC/hardware/SS_pipes_umoxvz.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662838221/PTC/hardware/SS_pipes_u6berl.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662838221/PTC/hardware/SS_pipes_u6berl.webp",
      ],
      seller: "Jindal",
      pdf: "https://drive.google.com/file/d/12U3mQ_-nQXl36y3cIK5rd8UG76ER2sq2/view?usp=sharing",
      desp: "Jindal Star a brand of a D.P. Jindal Group has three manufacturing units located in Ghaziabad (Uttar Pradesh), Nagothane (Maharashtra) and Bellary (Karnataka), with a production capacity of 5,00, 000 MT ERW Pipes and Tubes with a thickness from 2.00 mm to 12.7 mm having an outer Diameter ranging from 1/2” to 20” NB as per specifications of IS, BS, API, ASTM, DIN, IBR which conforms to the various international standards. These products are widely used across various industries like agriculture, oil, refinery, public health, housing, irrigation, engineering, fire fighting, tubular poles and structural etc. The company’s Black & Galvanized ERW Steel Tubes Conforming to IS: 1239, IS:3589 ,IS:1161, API 5L (Line Pipe) are few of the largest selling models catering to Plumbing, MEP works, Structural and Oil and Gas applications.",
      link: "https://www.jindal.com/",
      category: "hardware",
    },
    {
      id: 19,
      name: "Agriculture Products",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662841187/PTC/hardware/Agriculture_1_pa1liu.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662841187/PTC/hardware/aricultural_3_jtojx2.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662841187/PTC/hardware/Agriculture_2_aserga.jpg",
      ],
      seller: "TATA AGRICO",
      pdf: "https://drive.google.com/file/d/19RgDiBZYUTxi0AdabzlCU7dZffuRhR-j/view?usp=sharing",
      desp: "Founded by Jamsetji Tata in 1868, the Tata group is a global enterprise headquartered in India, comprising over 100 operating companies in seven business sectors: communications and information technology, engineering, materials, services, energy, consumer products and chemicals. The group has operations in more than 100 countries across six continents, and its companies export products and services to 150 countries. The revenue of Tata companies, taken together, was $103.27 billion (around Rs. 624,757 crore) in 2013-14, with 67.2 percent of this coming from businesses outside India. Tata companies employ over 581,470 people worldwide. Brand Finance, a UK-based consultancy firm, valued the Tata brand at $21.1 billion and ranked it 34th among the top 500 most valuable global brands in their BrandFinance® Global 500 2014 report. Bombay House The Tata name has been respected for more than 140 years for its adherence to strong values and the group has always believed in returning wealth to the society it serves. Two-thirds of the equity of Tata Sons, the Tata group holding company, is held by philanthropic trusts that have created national institutions for science and technology, medical research, social studies and the performing arts.",
      link: "https://www.tataagrico.com/#about",
      category: "hardware",
    },
    {
      id: 20,
      name: "Castex Trolley Wheel",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662839207/PTC/hardware/Trolley_wheel_2_a7o0qq.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662839207/PTC/hardware/Trolley_wheel_3_opuln5.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662839207/PTC/hardware/Trolley_wheel_1_mtfrxm.jpg",
      ],
      seller: "APEX",
      pdf: "https://drive.google.com/file/d/1WwnnTLzTxc_Y0lg7RO_68ynURjaza2Ne/view?usp=sharing",
      desp: "Bharat Industrial Corporation is the major supplier and manufacturer of Castor Wheels, Trolley Wheels and Platform Trolleys. Our range start from heavy duty, medium duty and light duty caster Wheels with vast variety of wheel like CP wheel, Nylon wheel, PU wheel, Rubber wheel, Cast Iron caster and many more. We have widely accepted brand series of APEX  a Premium brand of Bharat Industrial corporation. Our products are widely appreciated for their features like durability, fine finish and easy installation. Bharat Industrial Corporation- popularly known by (BIC), works on reputed image at National and international level. We are having a Team of Professionals, Market experienced experts to provide best solution to our customer and understand the demand of Indian Castor & Trolley wheels market. We are leading manufacturers of Heavy Duty, Medium Duty and Light Duty Caster Wheels with variety of wheels i.e CP wheel, Nylon wheel, PU wheel, Rubber wheel, Cast Iron wheel and many more. Our team is a fine mix of Creative Brains, Marketing; Communication & Strategies experts who help us deliver high impact solutions of APEX heavy duty caster wheels. BIC is recognized manufacturing house by the Government of India and has its presence in supplying heavy duty castor & trolley wheels, platform trolleys, ball transfer units, rollers, manual conveyors from last 19 years. Apex caster wheel had Pan India presence with multiple manufacturing units i.e. Bawal and Gurugram. We are also expanding our wings globally with some elite and reputed clients. We had deep penetration in Indian market of Caster wheel, Trolley Wheel and Platform Trolleys.",
      link: "https://www.apex.ooo/about-bic-apex.php",
      category: "hardware",
    },
    {
      id: 21,
      name: "Locks",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662841846/PTC/hardware/locks_1_hjrtch.png",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662841981/PTC/hardware/LOCKS_2_bgfwht.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662842018/PTC/hardware/LOCKS_3_p5tztx.jpg",
      ],
      seller: "Harrison",
      pdf: "https://drive.google.com/file/d/1276Y9Us_vzNgy5br2vBt2m3zMEGNnK5V/view?usp=sharing",
      desp: "Over 6 decades, Harrison which has been brand leader in locks & hardware solution. Be fealess & desire for more from HARRISON with a bold thinking and rigorous craftsmanship combine to bring innovative, sturdy products. Harrison a brand, is one of the leading company known for providing best security & hardwaresolutions. We're celebrating 65+ years of setting the standards of excellences and pushing the limits of product design. whether we are bringing to you.",
      link: "https://www.harrisonlocks.com/about/company-profile",
      category: "hardware",
    },
    {
      id: 22,
      name: "sanitary",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662842139/PTC/hardware/Sanitary_2_dgwhir.png",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658059921/PTC/hardware/product-500x500_ixu9sc.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662842138/PTC/hardware/Sanitary_1_x77jbj.jpg",
      ],
      seller: "Prince",
      pdf: "https://drive.google.com/file/d/1WwnnTLzTxc_Y0lg7RO_68ynURjaza2Ne/view?usp=sharing",
      desp: "One of the largest SKUs in the industry of over 7200 products. Prince is committed towards constant innovations in plumbing, irrigation and sewerage technologies to meet the nation’s constantly increasing water demands. Prince Pipes and Fittings Ltd. constantly strives to pave the way for a future that provides clean water for everyone and everywhere; from the smallest villages to the largest cities. Prince Pipes and Fittings Ltd. incorporates a well-structured framework, combined with state-of-the-art machinery that creates a zero defect manufacturing process and leak-proof piping systems. We operate computerized injection moulding machines with a clamping force ranging from 50 to 660 tons to manufacture fittings.",
      link: "https://www.princepipes.com/",
      category: "hardware",
    },
    {
      id: 23,
      name: "v-Belts",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656180688/PTC/hardware/v-belts_pwmdqu.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662842348/PTC/hardware/V-belt_3_cb58hh.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662842301/PTC/hardware/v_belt_2_zn2vzt.jpg",
      ],
      seller: "JK Fenner",
      pdf: "https://drive.google.com/file/d/1GEJXU-GfuysZ1HfSw-hm33CrsbOoUwrL/view?usp=sharing",
      desp: "In 1987 JK Fenner became a strategic investor in Fenner Cockill Limited and eventually acquired company in the year 2004. Right from the time of its Inception the name has been synonymous with Mechanical Power Transmission and Sealing Solutions. The company was acquired by JK Organisation in 1987, and currently, as a member of the conglomerate J.KFenner operates 5 state-of-the-art manufacturing units and 3 world-class Research & Development facilities. With quality, commitment and relentless service Fenner has established itself as the market leader for Power Transmission Belts in India catering to diverse industrial applications. J.K Fenner is also a name to reckon with in the design and manufacturing of Oil Seals, Hoses, Gear Boxes, Geared Motors, Pulleys, Power Transmission Belts, FEAD Systems, Belt Tensioners, and Moulded Rubber Products, EV Products for Automotive & Industrial Applications. The Organisation addresses the needs of major sectors like Steel, Cement, Coal, Sugar, Power, Paper, Textiles, Food processing, Agriculture and many more.",
      link: "https://jkfenner.com/industrial-power-transmission-belts/",
      category: "hardware",
    },

    {
      id: 24,
      name: "welding items",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656180996/PTC/hardware/welding_n2hno0.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658061752/PTC/hardware/download_4_ddklzc.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658061751/PTC/hardware/0f446d_2f56ce412b434427a3d312ead56743f5_mv2_r6drhu.webp",
      ],
      seller: "Borris",
      pdf: "https://drive.google.com/file/d/1ilIS1PkVr_5O77nECTD2UzJfZgpjPid7/view?usp=sharing",
      category: "hardware",
    },
    {
      id: 25,
      name: "weld mesh net",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662842468/PTC/hardware/weldmesh_nets_qwkdh9.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181146/PTC/hardware/net_i2b5yp.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658062599/PTC/hardware/download_5_tz49em.webp",
      ],
      seller: "Tiger Wire Mesh Nets",
      desp: "Tiger Brand is the most popular, renowned and trusted wire mesh brand of India for its unmatched quality and consistency. The brand enjoys unmatched reputation and is the undisputed leader in the industry. The trade mark brand name was adopted in 1964-65, and the manufacturing was established in 1958, by Late Sh. Prithvi Raj Ji, under the name of Calcutta Wire Netting Industries. It has since then followed the same foot steps and enlarged the scope of manufacturing varieties and presently can boast of having the maximum number of looms in India and a manifold types and other metal wire products.",
      link: "https://tigerwiremesh.com/",
      category: "hardware",
    },
    {
      id: 26,
      name: "tarpaulin",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181225/PTC/hardware/Tarpaulin_uoabyx.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658062872/PTC/hardware/download_7_xy8qyr.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658062861/PTC/hardware/download_8_mimgbg.webp",
      ],
      seller: "Supreme",
      desp: "Founded in 1942, Supreme is an acknowledged leader of India's plastics industry. Handling volumes of over 3,50,000 tonnes of polymers annually effectively makes the country's largest plastics processors. Not surprisingly, we also offer the widest and most comprehensive range of plastic products in India. Our 25 advanced plants are powered by technology from world leaders, and complement our extensive facilities for R & D and new product development. In fact, Supreme is credited with pioneering several products in India. These include Cross- Laminated Films, HMHD Films, Multilayer Films, SWR Piping Systems and more. Supreme Industries Limited is India's leading plastic processing company with seven business divisions. The company has forayed into different types of plastic processing in Injection Moulding, Rotational Moulding (ROTO), Extrusion, Compression Moulding, Blow Moulding etc.",
      link: "https://www.supreme.co.in/index.php",
      category: "hardware",
    },

    {
      id: 27,
      name: "MS & GI pipes",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656180582/PTC/hardware/MS_GI_pipes_wzwvu2.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658063642/PTC/hardware/download_10_pj350v.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658063643/PTC/hardware/download_9_jayxos.webp",
      ],
      seller: "Jindal",
      pdf: "https://drive.google.com/file/d/1mBjvMiL8H3MUOKu-qgrdnlxzJ5Hz_n0_/view?usp=sharing",
      desp: "Jindal Star a brand of a D.P. Jindal Group has three manufacturing units located in Ghaziabad (Uttar Pradesh), Nagothane (Maharashtra) and Bellary (Karnataka), with a production capacity of 5,00, 000 MT ERW Pipes and Tubes with a thickness from 2.00 mm to 12.7 mm having an outer Diameter ranging from 1/2” to 20” NB as per specifications of IS, BS, API, ASTM, DIN, IBR which conforms to the various international standards. These products are widely used across various industries like agriculture, oil, refinery, public health, housing, irrigation, engineering, fire fighting, tubular poles and structural etc. The company’s Black & Galvanized ERW Steel Tubes Conforming to IS: 1239, IS:3589 ,IS:1161, API 5L (Line Pipe) are few of the largest selling models catering to Plumbing, MEP works, Structural and Oil and Gas applications.",
      link: "https://www.jindal.com/",
      category: "hardware",
    },
    {
      id: 28,
      name: "insulation items",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181498/PTC/hardware/Insulation_ms0wzl.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658063913/PTC/hardware/download_12_tuccwy.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658063922/PTC/hardware/download_11_ltyfam.webp",
      ],
      seller: "Shreeram Equitech Pvt Ltd",
      desp: "We live in the present age of ever increasing cost of fuels, which in turn leads to increased cost of production and end productions. In this context of rapid growth of energy intensive industries in our country and overseas, updating thermal insulation standards, development of superior materials and evolution of speedier manufacturing techniques are the need of the hour. We, at Shree Ram Equitech Pvt. Ltd., have taken up the challenge of producing complete range of insulation products, as per Indian and International Standards. The company has set up a 14400 MTPA capacity plant at Rasmada Industrial Area, Durg, Chhattisgarh with ultra modern facilities and sophisticated infra structures. The company is spread all over India with Head Office at Durg and Regional Sales Offices at Delhi, Kolkatta, Pune, Hyderabad and Chennai.",
      link: "https://www.indiamart.com/shreeram-equitech-pvt-ltd/aboutus.html",
      category: "hardware",
    },
    {
      id: 29,
      name: "measuring items",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181576/PTC/hardware/Measuring-Items-1_pp0brc.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658064378/PTC/hardware/download_13_dzllun.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658064379/PTC/hardware/download_14_wqe5yx.webp",
      ],
      seller: "Freemans",
      pdf: "https://drive.google.com/file/d/11jRrLuyLdFcrx62RGq2_cVecsMdGnoAS/view?usp=sharing",
      desp: "Founded in 1950, FMI Limited is the largest manufacturer of measuring tapes, spirit levels and measuring wheels in the Indian sub-continent. We are a highly vertically integrated measuring tape manufacturing company, with state of the art in-house injection moulding and steel cold rolling facilities. In 2018, we achieved our long term ambition of manufacturing more than 100,000 high quality measuring tapes per day. The FREEMANS product portfolio now extends beyond linear measurement tools to encompass a wide range of hand tools, precision measuring tools, digital measuring tools and power tool accessories.",
      link: "https://www.freemansgroup.com/",
      category: "hardware",
    },
    {
      id: 30,
      name: "bearings",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181734/PTC/hardware/Bearings_m9gmmx.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658064515/PTC/hardware/download_16_byudf9.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658064516/PTC/hardware/download_15_nsrb9c.webp",
      ],
      seller: "NBC Bearings",
      pdf: "https://drive.google.com/file/d/1EXe7w04DjGN9YF3jj-uXx8v4EoSRytnM/view?usp=sharing",
      desp: "A symbol of dependability and flexible engineering solutions, NBC Bearings is the brand of National Engineering Industries. Founded in 1946, National Engineering Industries Ltd (NEI) is India’s leading bearings manufacturer and exporter, renowned for excellence in quality and delivery. Headquartered in Jaipur, NEI is an integral part of the US$ 2.4 bn CK Birla Group. Having started with 30,000 bearings in 19 sizes in 1946, NEI has evolved to manufacture over 200 million bearings each year offered in more then 2300 variants to serve a host of customers in India and 30 other countries across five continents in automotive, railways and industrial segments. NEI also serves the Indian aftermarket through a countrywide network of 550 authorized stockists.",
      link: "https://nbcbearings.com/",
      category: "hardware",
    },
    {
      id: 31,
      name: "tools & accessories ",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181818/PTC/hardware/Tools-nd-accessories_ujrsuw.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658064727/PTC/hardware/taparia-hand-tools-500x500-500x500_jm6yoi.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658064728/PTC/hardware/download_17_hho3wp.webp",
      ],
      seller: "Taparia",
      pdf: "https://drive.google.com/file/d/1dt3EXrLKZNtbp4-9uioK8SxjpgptXhjW/view?usp=sharing",
      desp: "The company has a well laid out fully equipped factory located at Nashik, which is about four hours drive from the city of Mumbai in Western India and another expanded unit at Goa, approx 600 kilometers from Mumbai. The plant is located on a total area of 42832 Sq.Mtrs. All the manufacturing facilities required for production of hand tools are under one roof – one location. Hand tools manufacturing is complicated involving high technology and labor intensive production process. Out of the total of 1200 work force of this, the number of people engaged in direct production is 1000. The remaining are in administrative and management. The company’s research and development department is manned by Mechanical Engineers and Metallurgists equipped with latest CAD design facilities etc.From its inception, the company has laid high emphasis on the quality of its products. It has well established quality control department to monitor the quality of the product at different stages of production. In fact Taparia tools meet and some cases exceed the U.S. Federal Specifications of hardness and torque value besides meeting Indian, British and German standards. Taparia tools are guaranteed against manufacturing and raw material defects and are replaced free with no question asked.",
      link: "https://www.tapariatools.com/",
      category: "hardware",
    },
  ];
};

const steelItems = () => {
  return [
    // !pdfs and the other inpage content will also be included in this  (another array can be made in the items array!)
    {
      id: 51,
      name: "MS Angle",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662842975/PTC/hardware/MS_angle_uypkyw.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072065/PTC/hardware/images_1_jdnj4c.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181970/PTC/steel/Shapes_and_sections_zjrex8.webp",
      ],
      category: "steel",
    },
    {
      id: 52,
      name: "MS Beam",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662842974/PTC/hardware/beam_vrurjy.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072065/PTC/hardware/images_1_jdnj4c.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181970/PTC/steel/Shapes_and_sections_zjrex8.webp",
      ],
      category: "steel",
    },
    {
      id: 53,
      name: "MS Channel",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662843089/PTC/hardware/MS_channel_pepi6q.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072065/PTC/hardware/images_1_jdnj4c.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656181970/PTC/steel/Shapes_and_sections_zjrex8.webp",
      ],
      category: "steel",
    },
    {
      id: 54,
      name: "round & square pipes",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072165/PTC/hardware/download_19_fih1cx.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656182107/PTC/steel/Round_and_square_pipes_rn1vmq.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072164/PTC/hardware/download_18_ylqg0z.webp",
      ],
      category: "steel",
    },
    {
      id: 55,
      name: "MS bar",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656182146/PTC/steel/Ms_bars_myrlpw.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072405/PTC/hardware/download_22_g5aqax.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072405/PTC/hardware/images_2_n6puro.webp",
      ],
      category: "steel",
    },
    {
      id: 57,
      name: "MS sheet & plate",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1662843330/PTC/steel/MS_Sheet_and_Plate_cklqe7.jpg",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072285/PTC/hardware/download_20_awlmrw.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072288/PTC/hardware/download_21_ekeue0.webp",
      ],
      category: "steel",
    },
    {
      id: 58,
      name: "GI Sheet and Coil",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656182218/PTC/steel/Coil_and_plate_bhkmfm.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072285/PTC/hardware/download_20_awlmrw.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072288/PTC/hardware/download_21_ekeue0.webp",
      ],
      category: "steel",
    },

    {
      id: 58,
      name: "flat (MS & SS)",
      img: [
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072481/PTC/hardware/images_3_qbtidy.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1656182263/PTC/steel/AnyConv.com__Flats_MS_GI_ddrf8o.webp",
        "https://res.cloudinary.com/dlghjr9qx/image/upload/v1658072480/PTC/hardware/download_23_rnfalr.webp",
      ],
      category: "steel",
    },
  ];
};

export { hardwareItems, steelItems };
